version: '2'
services:

  archimedes1:
    extends:
      file: docker-compose-base.yml
      service: base
    image: "storyteller/archimedes"
    ports:
     - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: archimedes1
      
  archimedes2:
    extends:
      file: docker-compose-base.yml
      service: base
    image: "storyteller/archimedes"
    ports:
     - "8762:8762"
    environment:
      SPRING_PROFILES_ACTIVE: archimedes2
     
  my-rabbit:
    extends:
      file: docker-compose-base.yml
      service: base
    image: "rabbitmq:3"
    ports:
     - "5672:5672"
      
  config-server:
    extends:
      file: docker-compose-base.yml
      service: base
    image: "storyteller/config-server"
    ports:
     - "8888:8888"
    depends_on:
      - my-rabbit
     
  gatekeeper:
    extends:
      file: docker-compose-base.yml
      service: base
    image: "storyteller/gatekeeper"
    ports:
     - "9966:9966"
    depends_on:
      - archimedes1
      - archimedes2
      - config-server

  central-logger1:
    extends:
      file: docker-compose-base.yml
      service: base
    image: "storyteller/central-logger-ms"
    ports:
     - "12021:12021"
    environment:
      SPRING_PROFILES_ACTIVE: cl1
    depends_on:
      - archimedes1
      - archimedes2
      - config-server
      
  central-logger2:
    extends:
      file: docker-compose-base.yml
      service: base
    image: "storyteller/central-logger-ms"
    ports:
     - "21012:21012"
    environment:
      SPRING_PROFILES_ACTIVE: cl2
    depends_on:
      - archimedes1
      - archimedes2
      - config-server
      
  log-processor1:
    extends:
      file: docker-compose-base.yml
      service: base
    image: "storyteller/log-processor-ms"
    ports:
     - "14041:14041"
    environment:
      SPRING_PROFILES_ACTIVE: lp1
    depends_on:
      - archimedes1
      - archimedes2
      - config-server
      
  log-processor2:
    extends:
      file: docker-compose-base.yml
      service: base
    image: "storyteller/log-processor-ms"
    ports:
     - "41014:41014"
    environment:
      SPRING_PROFILES_ACTIVE: lp2
    depends_on:
      - archimedes1
      - archimedes2
      - config-server


  storyteller-api1:
    extends:
      file: docker-compose-base.yml
      service: base
    image: "storyteller/storyteller-api"
    ports:
     - "9977:9977"
    environment:
      SPRING_PROFILES_ACTIVE: storyteller-api1
    depends_on:
      - gatekeeper
      
  storyteller-api2:
    extends:
      file: docker-compose-base.yml
      service: base
    image: "storyteller/storyteller-api"
    ports:
     - "7799:7799"
    environment:
      SPRING_PROFILES_ACTIVE: storyteller-api2
    depends_on:
      - gatekeeper
   
  images1:
    extends:
      file: docker-compose-base.yml
      service: base
    image: "storyteller/images-ms"
    ports:
     - "9999:9999"
    environment:
      SPRING_PROFILES_ACTIVE: images1
    depends_on:
      - gatekeeper
      
  images2:
    extends:
      file: docker-compose-base.yml
      service: base
    image: "storyteller/images-ms"
    ports:
     - "9998:9998"
    environment:
      SPRING_PROFILES_ACTIVE: images2
    depends_on:
      - gatekeeper
      
  stories1:
    extends:
      file: docker-compose-base.yml
      service: base
    image: "storyteller/stories-ms"
    ports:
     - "9988:9988"
    environment:
      SPRING_PROFILES_ACTIVE: stories1
    depends_on:
      - gatekeeper
      
  stories2:
    extends:
      file: docker-compose-base.yml
      service: base
    image: "storyteller/stories-ms"
    ports:
     - "9987:9987"
    environment:
      SPRING_PROFILES_ACTIVE: stories2
    depends_on:
      - gatekeeper
      
  hystrix-dashboard:
    extends:
      file: docker-compose-base.yml
      service: base
    image: "storyteller/hystrix-dashboard"
    ports:
      - "10000:10000"
    depends_on:
      - gatekeeper
     